name: Bot de Vagas Diário

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  correr-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o código
        uses: actions/checkout@v4

      - name: Preparar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar o Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: python scraper.py